server:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
  persistentVolume:
    enabled: true
    size: 2Gi
  retention: 1d

alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
